# AIML with Applied Mathematics — Lab Program 1

## Scientific Computing

**CO Mapping:** CO1

This notebook is prepared for direct execution in **Google Colab**. Run the installation cell first, then run the program cell.

### 1. Install required packages

In [1]:
!pip install -q numpy pandas matplotlib scipy scikit-learn


[notice] A new release of pip available: 22.3.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip


### 2. Execute the complete lab program

In [1]:

"""
LAB PROGRAM 1
Scientific computing framework using Python, NumPy and Pandas.

Covers:
- vector/matrix operations
- matrix multiplication, inverse, determinant
- linear transformation
- DataFrame creation/manipulation
- statistical computations
- ML-oriented example
"""
import numpy as np
import pandas as pd

np.set_printoptions(precision=4, suppress=True)

# ---------------- 1. Vectors ----------------
v = np.array([2, 3, 4])
w = np.array([1, 5, 2])

print("VECTOR OPERATIONS")
print("v =", v)
print("w =", w)
print("v + w =", v + w)
print("v - w =", v - w)
print("2v =", 2*v)
print("Dot product =", np.dot(v, w))
print("||v|| =", np.linalg.norm(v))

# ---------------- 2. Matrices ----------------
A = np.array([[2, 1], [1, 3]], dtype=float)
B = np.array([[4, 2], [0, 5]], dtype=float)

print("\nMATRIX OPERATIONS")
print("A + B =\n", A+B)
print("A @ B =\n", A@B)
print("B @ A =\n", B@A)
print("det(A) =", np.linalg.det(A))
print("A^-1 =\n", np.linalg.inv(A))

# Solve Ax=b
b = np.array([5, 7], dtype=float)
x = np.linalg.solve(A, b)
print("Solution of Ax=b:", x)
print("Verification A@x:", A@x)

# ---------------- 3. Linear transformation ----------------
theta = np.deg2rad(45)
R = np.array([[np.cos(theta), -np.sin(theta)],
              [np.sin(theta),  np.cos(theta)]])
point = np.array([1., 0.])
rotated = R @ point

print("\nLINEAR TRANSFORMATION")
print("Rotation matrix:\n", R)
print("Original point:", point)
print("Rotated point:", rotated)

# ---------------- 4. Pandas ----------------
df = pd.DataFrame({
    "Student": ["A","B","C","D","E"],
    "Hours": [2, 4, 5, 7, 8],
    "Attendance": [70, 80, 75, 90, 95],
    "Marks": [45, 55, 60, 72, 80]
})

print("\nDATAFRAME")
print(df)

print("\nDescriptive statistics:")
print(df[["Hours","Attendance","Marks"]].describe())

df["Pass"] = np.where(df["Marks"] >= 50, 1, 0)
print("\nAfter feature creation:")
print(df)

print("\nCorrelation matrix:")
print(df[["Hours","Attendance","Marks"]].corr())

# ---------------- 5. ML significance ----------------
# Simple matrix form y = Xw
X = np.column_stack([
    np.ones(len(df)),
    df["Hours"].values,
    df["Attendance"].values
])
y = df["Marks"].values

w_ls = np.linalg.pinv(X) @ y
pred = X @ w_ls

print("\nLEAST-SQUARES ML EXAMPLE")
print("Learned parameters [intercept, hours, attendance] =", w_ls)
print("Predicted marks =", pred)
print("MSE =", np.mean((y-pred)**2))

print("\nInterpretation: NumPy provides the mathematical operations, while Pandas handles structured data used by ML pipelines.")


VECTOR OPERATIONS
v = [2 3 4]
w = [1 5 2]
v + w = [3 8 6]
v - w = [ 1 -2  2]
2v = [4 6 8]
Dot product = 25
||v|| = 5.385164807134504

MATRIX OPERATIONS
A + B =
 [[6. 3.]
 [1. 8.]]
A @ B =
 [[ 8.  9.]
 [ 4. 17.]]
B @ A =
 [[10. 10.]
 [ 5. 15.]]
det(A) = 5.000000000000001
A^-1 =
 [[ 0.6 -0.2]
 [-0.2  0.4]]
Solution of Ax=b: [1.6 1.8]
Verification A@x: [5. 7.]

LINEAR TRANSFORMATION
Rotation matrix:
 [[ 0.7071 -0.7071]
 [ 0.7071  0.7071]]
Original point: [1. 0.]
Rotated point: [0.7071 0.7071]

DATAFRAME
  Student  Hours  Attendance  Marks
0       A      2          70     45
1       B      4          80     55
2       C      5          75     60
3       D      7          90     72
4       E      8          95     80

Descriptive statistics:
          Hours  Attendance      Marks
count  5.000000    5.000000   5.000000
mean   5.200000   82.000000  62.400000
std    2.387467   10.368221  13.831124
min    2.000000   70.000000  45.000000
25%    4.000000   75.000000  55.000000
50%    5.000000   8

### 3. Student observations

- Record the important outputs/plots generated above.
- Change at least one parameter and rerun the experiment.
- Compare the new result with the original result.
- Record the inference in the lab record.